#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: Proyecto ICCD332 Arquitectura de Computadores
#+date: 2026-07-14
#+author:Leonardo Rodriguez, Evan Matango, Henry Luisa, Jonathan Pincay
#+email: leonardo.rodriguez01@epn.edu.ec
#+language: es
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.7.5)
#+cite_export:
* City Weather APP
Este es el proyecto de fin de semestre en donde se pretende demostrar
las destrezas obtenidas durante el transcurso de la asignatura de
**Arquitectura de Computadores**.

1. Conocimientos de sistema operativo Linux
2. Conocimientos de Emacs/Jupyter
3. Configuración de Entorno para Data Science con Mamba/Anaconda
4. Literate Programming
 
** Estructura del proyecto
Se recomienda que el proyecto se cree en el /home/ del sistema
operativo i.e. /home/<user>/. Allí se creará la carpeta /CityWeather/
#+begin_src shell :results output :exports both
cd /home/eareal/Arquitectura-/ProyectoNewYork
pwd
#+end_src

#+RESULTS:
: /home/QuitoWeather

El proyecto ha de tener los siguientes archivos y
subdirectorios. Adaptar los nombres de los archivos según las ciudades
específicas del grupo.

#+begin_src shell :results output :exports results
cd /home/eareal/Arquitectura-/ProyectoNewYork
tree
#+end_src

#+RESULTS:
#+begin_example
.
├── #index.org#
├── CityTemperatureAnalysis.ipynb
├── clima-newyork-hoy.csv
├── get-weather.sh
├── get-weather.sh~
├── index.org
├── index.org:Zone.Identifier
├── index.org~
├── main.py
├── main.py~
├── output.log
└── weather-site
    ├── build-site.el
    ├── build.sh
    ├── content
    │   ├── images
    │   ├── index.org
    │   └── page2-js.org
    └── public
        ├── images
        └── index.h

6 directories, 16 files
#+end_example

Puede usar Emacs para la creación de la estructura de su proyecto
usando comandos desde el bloque de shell. Recuerde ejecutar el bloque
con ~C-c C-c~. Para insertar un bloque nuevo utilice ~C-c C-,~ o ~M-x
org-insert-structure-template~. Seleccione la opción /s/ para src y
adapte el bloque según su código tenga un comandos de shell, código de
Python o de Java. En este documento ~.org~ dispone de varios ejemplos
funcionales para escribir y presentar el código.

#+begin_src shell :results output :exports both
echo 'Aquí va sus comandos'
#+end_src

#+RESULTS:
: Aquí va sus comandos

** Formulación del Problema
Se desea realizar un registro climatológico de New York. Para esto,
escriba un script de Python/Java que permita obtener datos
climatológicos desde el API de [[https://openweathermap.org/current#one][openweathermap]]. El API hace uso de los
valores de latitud $x$ y longitud $y$ de la ciudad $\mathcal{C}$ para
devolver los valores actuales a un tiempo $t$.

Los resultados obtenidos de la consulta al API se escriben en un
archivo /clima-newyork-hoy.csv . Cada ejecución del script debe
almacenar nuevos datos en el archivo. Utilice *crontab* y sus
conocimientos de Linux y Programación para obtener datos del API de
/openweathermap/ con una periodicidad de 15 minutos mediante la
ejecución de un archivo ejecutable denominado
/get-weather.sh/. Obtenga al menos 50 datos. Verifique los
resultados. Todas las operaciones se realizan en Linux o en el
WSL. Las etapas del problema se subdividen en:

    1. Conformar los grupos de 2 estudiantes y definir la ciudad
       objeto de estudio.
    2.  Crear su API gratuito en [[https://openweathermap.org/current#one][openweathermap]]
    3. Escribir un script en Python/Java que realice la consulta al
       API y escriba los resultados en /clima-<ciudad>-hoy.csv/. El
       archivo ha de contener toda la información que se obtiene del
       API en columnas. Se debe observar que los datos sobre lluvia
       (rain) y nieve (snow) se dan a veces si existe el fenómeno.
    3. Desarrollar un ejecutable /get-weather.sh/ para ejecutar el
       programa Python/Java.[fn:1]
       #+begin_src shell :exports both
         cat get-weather.sh
       #+end_src

       #+RESULTS:
       | #!/usr/bin/bash |                                            |          |    |         |         |          |         |          |         |      |       |         |    |    |           |
       |                 |                                            |          |    |         |         |          |         |          |         |      |       |         |    |    |           |
       | #               | 1                                          | Navegar  | a  | la      | carpeta | de       | tu      | proyecto | (CAMBIA | ESTA | RUTA) |         |    |    |           |
       | cd              | /home/eareal/Arquitectura-/ProyectoNewYork |          |    |         |         |          |         |          |         |      |       |         |    |    |           |
       |                 |                                            |          |    |         |         |          |         |          |         |      |       |         |    |    |           |
       | #               | 2                                          | Activar  | el | entorno | de      | Anaconda | (Ajusta | el       | nombre  | de   | tu    | entorno | si | es | distinto) |
       | source          | ~/miniforge3/etc/profile.d/conda.sh        |          |    |         |         |          |         |          |         |      |       |         |    |    |           |
       | conda           | activate                                   | iccd332  |    |         |         |          |         |          |         |      |       |         |    |    |           |
       |                 |                                            |          |    |         |         |          |         |          |         |      |       |         |    |    |           |
       | #               | 3                                          | Ejecutar | el | script  | de      | Python   |         |          |         |      |       |         |    |    |           |
       | python          | main.py                                    |          |    |         |         |          |         |          |         |      |       |         |    |    |           |

    4. Configurar Crontab para la adquisición de datos. Escriba el
       comando configurado. Respalde la ejecución de crontab en un
       archivo output.log
    5. Realizar la presentación del Trabajo utilizando la generación
       del sitio web por medio de Emacs. Para esto es necesario crear
       la carpeta **weather-site** dentro del proyecto. Puede ajustar el
       /look and feel/ según sus preferencias. El servidor a usar es
       el **simple-httpd** integrado en Emacs que debe ser instalado:
       - Usando comandos Emacs: ~M-x package-install~ presionamos
         enter (i.e. RET) y escribimos el nombre del paquete:
         simple-httpd
       - Configurando el archivo init.el

       #+begin_src elisp
         (use-package simple-httpd
            :ensure t)
       #+end_src

       Instrucciones de sobre la creación del sitio web se tiene en el
       vídeo de instrucciones y en el archivo [[https://github.com/LeninGF/EPN-Lectures/blob/main/iccd332ArqComp-2024-A/Tutoriales/Org-Website/Org-Website.org][Org-Website.org]] en el
       GitHub del curso

    6. Su código debe estar respaldado en GitHub/BitBucket, la
       dirección será remitida en la contestación de la tarea
** Descripción del código
En esta sección se debe detallar segmentos importantes del código
desarrollado así como la **estrategia de solución** adoptada por el
grupo para resolver el problema. Divida su código en unidades
funcionales para facilitar su presentación y exposición.

Lectura del API
#+begin_src python :session :results output exports both
import requests

API_KEY = "c8fb29956631fe51156dd54569038b53" # Aquí va tu clave real
LAT = 40.7128  # Latitud de New York
LON = -74.0060 # Longitud de New York
URL = f"https://api.openweathermap.org/data/2.5/weather?lat={LAT}&lon={LON}&appid={API_KEY}&units=metric"

respuesta = requests.get(URL)
print(f"Código de respuesta de la API: {respuesta.status_code}")
#+end_src

#+RESULTS:
: Código de respuesta de la API: 200

Puede tener que borrar los dos puntos para que el resultado aparezca
en el HTML. En mi caso no fue necesario. Pruebe.
#+RESULTS:
: 8

Convertir /Json/ a /Diccionario/ de Python
#+begin_src python :session :results output exports both
if respuesta.status_code == 200:
    datos = respuesta.json()
    temperatura = datos["main"]["temp"]
    humedad = datos["main"]["humidity"]
    presion = datos["main"]["pressure"]
    clima_principal = datos["weather"][0]["main"]
    
    print(f"Temp: {temperatura}°C, Humedad: {humedad}%, Clima: {clima_principal}")
#+end_src

#+RESULTS:
: Temp: 32.2°C, Humedad: 51%, Clima: Clouds


Guardar el archivo csv
#+begin_src python :session :results output exports both
import csv
from datetime import datetime

# Obtenemos lluvia y nieve (si no hay, ponemos 0)
lluvia_1h = datos.get("rain", {}).get("1h", 0)
nieve_1h = datos.get("snow", {}).get("1h", 0)
fecha_hora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

linea = [fecha_hora, temperatura, humedad, presion, clima_principal, lluvia_1h, nieve_1h]

with open('/home/eareal/Arquitectura-/ProyectoNewYork/clima-newyork-hoy.csv', mode='a', newline='') as archivo:
    writer = csv.writer(archivo)
    writer.writerow(linea)

print("Datos de New York guardados exitosamente.")
#+end_src

#+RESULTS:
: Datos de New York guardados exitosamente.

** Script ejecutable sh
Se coloca el contenido del script ejecutable. Recuerde que se debe
utilizar el entorno de **anaconda/mamba** denominado **iccd332** para
la ejecución de Python; independientemente de que tenga una
instalación nativa de Python.

En el caso de los shell script se puede usar `which sh` para conocer
la ubicación del ejecutable.
#+begin_src shell :results output :exports both
which sh
#+end_src

#+RESULTS:
: /usr/bin/sh

De igual manera se requiere localizar el entorno de mamba *iccd332*
que será utilizado.
#+begin_src shell :results output :exports both
which mamba
#+end_src

Con esto, el archivo ejecutable `get-weather.sh` tiene el siguiente código adaptado para la ciudad de New York y nuestro entorno de trabajo:

#+begin_src shell :exports code
#!/usr/bin/bash
cd /home/eareal/Arquitectura-/ProyectoNewYork
source /home/eareal/miniforge3/etc/profile.d/conda.sh
eval "$(conda shell.bash hook)"
conda activate iccd332
python3 main.py
#+end_src

Finalmente, se le dieron permisos de ejecución al archivo con el siguiente comando, tal como se explicó en clases:
#+begin_src shell :results output :exports both
chmod +x get-weather.sh
#+end_src

#+RESULTS:

** Configuración de Crontab
Se indica la configuración realizada en crontab para la adquisición de datos.

#+begin_src shell
*/15 * * * * /home/eareal/Arquitectura-/ProyectoNewYork/get-weather.sh >> /home/eareal/Arquitectura-/ProyectoNewYork/output.log 2>&1
#+end_src
* Presentación de resultados
Para la pressentación de resultados se utilizan las librerías de Python:
- matplotlib
- pandas

Alternativamente como pudo estudiar en el Jupyter Notebook
[[https://github.com/LeninGF/EPN-Lectures/blob/main/iccd332ArqComp-2024-A/Proyectos/CityWeather/CityTemperatureAnalysis.ipynb][CityTemperatureAnalysis.ipynb]], existen librerías alternativas que se
pueden utilizar para presentar los resultados gráficos. En ambos
casos, para que funcione los siguientes bloques de código, es
necesario que realice la instalación de los paquetes usando ~mamba
install <nombre-paquete>~
** Muestra Aleatoria de datos
Presentar una muestra de 10 valores aleatorios de los datos obtenidos.
#+caption: Lectura de archivo csv
#+begin_src python :session :results output exports both
import os
import pandas as pd
# lectura del archivo csv obtenido para New York
df = pd.read_csv('/home/eareal/Arquitectura-/ProyectoNewYork/clima-newyork-hoy.csv')
# se imprime la estructura del dataframe en forma de filas x columnas
print(df.shape)
#+end_src

#+RESULTS:
: (37, 7)


#+caption: Despliegue de datos aleatorios
#+begin_src python :session :exports both :results value table :return table
table1 = df.sample(10)
table = [list(table1)]+[None]+table1.values.tolist()
#+end_src

#+RESULTS:
| fecha_hora          | temperatura | humedad | presion | clima_principal | lluvia_1h | nieve_1h |
|---------------------+-------------+---------+---------+-----------------+-----------+----------|
| 2026-07-14 14:00:04 |       33.59 |      48 |    1015 | Clear           |         0 |        0 |
| 2026-07-14 12:00:03 |       31.96 |      50 |    1017 | Clouds          |         0 |        0 |
| 2026-07-14 12:30:03 |        31.9 |      51 |    1017 | Clouds          |         0 |        0 |
| 2026-07-14 17:30:08 |       33.23 |      50 |    1012 | Clouds          |         0 |        0 |
| 2026-07-14 13:00:04 |       32.91 |      49 |    1016 | Clouds          |         0 |        0 |
| 2026-07-14 13:15:03 |       33.06 |      48 |    1016 | Clouds          |         0 |        0 |
| 2026-07-14 18:45:02 |        32.2 |      51 |    1012 | Clouds          |         0 |        0 |
| 2026-07-14 10:15:04 |        29.6 |      55 |    1018 | Clouds          |         0 |        0 |
| 2026-07-14 00:43:02 |       23.55 |      67 |    1019 | Clouds          |         0 |        0 |
| 2026-07-14 18:36:18 |        32.2 |      51 |    1012 | Clouds          |         0 |        0 |

** Gráfica Temperatura vs Tiempo
Realizar una gráfica de la Temperatura en el tiempo.

#+begin_src python :results output :exports both :session
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import os

# TRUCO: Forzamos la creación de la carpeta "images" en donde sea que estemos
os.makedirs('./images', exist_ok=True)

# Aseguramos que la columna de fecha sea reconocida correctamente
df['fecha_hora'] = pd.to_datetime(df['fecha_hora'])

# Define el tamaño de la figura de salida
fig = plt.figure(figsize=(8,6))
plt.plot(df['fecha_hora'], df['temperatura'], marker='o', color='tab:blue', linestyle='-') 

plt.grid()
plt.title('Main Temp vs Time in New York')
plt.xlabel('Fecha y Hora')
plt.ylabel('Temperatura (°C)')
plt.xticks(rotation=40)
fig.tight_layout()

# Guardar imagen
plt.savefig('./images/temperature.png')
print("¡ÉXITO! Gráfica de temperatura generada.")
#+end_src

#+caption: Gráfica Temperatura vs Tiempo
#+RESULTS:
: ¡ÉXITO! Gráfica de temperatura generada.
** Realice una gráfica de Humedad con respecto al tiempo

#+begin_src python :results output :exports both :session
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# Aseguramos que la columna de fecha sea reconocida correctamente
df['fecha_hora'] = pd.to_datetime(df['fecha_hora'])

# Define el tamaño de la figura de salida
fig = plt.figure(figsize=(8,6))
plt.plot(df['fecha_hora'], df['humedad'], marker='s', color='tab:orange', linestyle='-') 

plt.grid()
plt.title('Humedad vs Time in New York')
plt.xlabel('Fecha y Hora')
plt.ylabel('Humedad (%)')
plt.xticks(rotation=40)
fig.tight_layout()

# Guardar imagen
plt.savefig('./images/humidity.png')
print("Gráfica de humedad generada")
#+end_src

#+RESULTS:
: Gráfica de humedad generada

#+caption: Gráfica Humedad vs Tiempo
#+RESULTS:

* Siguiente Sección
Para revisar la demostración matemática y el algoritmo de la asignatura de Arquitectura de Computadores, por favor diríjase a la siguiente página:
[[file:page2-js.org][Ver sección de Multiplicación IEEE 754]]
* Referencias
- [[https://emacs.stackexchange.com/questions/28715/get-pandas-data-frame-as-a-table-in-org-babel][presentar dataframe como tabla en emacs org]]
- [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-python.html][Python Source Code Blocks in Org Mode]]
- [[https://systemcrafters.net/publishing-websites-with-org-mode/building-the-site/][Systems Crafters Construir tu sitio web con Modo Emacs Org]]
- [[https://www.youtube.com/watch?v=AfkrzFodoNw][Vídeo Youtube Build Your Website with Org Mode]]
* Footnotes

[fn:1] Recuerde que su máquina ha de disponer de un entorno de
anaconda/mamba denominado iccd332 en el cual se dispone del interprete
de Python
